/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package twx.pdf;

import java.util.Scanner;
import java.util.Date;
import java.util.TimeZone;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Calendar;

import org.joda.time.*;
import org.joda.time.format.*;
import org.joda.time.Period;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {

	final static Logger logger  = LoggerFactory.getLogger(App.class);
   
    public static void main(String[] args) {
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"));
        var app 	= new App();
        var scanner	= new Scanner(System.in);
        
        logger.info("---------- Start-App ----------");
        try {

		}
        catch(Exception ex) {
            logger.error(ex.getMessage());
        }
        logger.info( "---------- Exit-App ----------");
    }
}
